In [2]:
import nba_py

In [8]:
scoreboard = nba_py.Scoreboard(month=5, day=4, year=2017)

In [9]:
scoreboard.game_header()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,WH_STATUS
0,2017-05-04T00:00:00,1,0041600203,3,Final,20170504/BOSWAS,1610612764,1610612738,2016,4,,ESPN,Q4 - ESPN,1
1,2017-05-04T00:00:00,2,0041600222,3,Final,20170504/UTAGSW,1610612744,1610612762,2016,4,,ESPN,Q4 - ESPN,1

In [10]:
scoreboard.series_standings()

,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,GAME_DATE_EST,HOME_TEAM_WINS,HOME_TEAM_LOSSES,SERIES_LEADER
0,0041600222,1610612744,1610612762,2017-05-04T00:00:00,2,0,Golden State
1,0041600203,1610612764,1610612738,2017-05-04T00:00:00,1,2,Boston

In [11]:
scoreboard.available()

      GAME_ID  PT_AVAILABLE
0  0041600203             1
1  0041600222             1

In [12]:
scoreboard.line_score()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,...,PTS_OT8,PTS_OT9,PTS_OT10,PTS,FG_PCT,FT_PCT,FG3_PCT,AST,REB,TOV
0,2017-05-04T00:00:00,1,0041600203,1610612738,BOS,Boston,2-1,17,23,29,...,0,0,0,89,0.351,0.758,0.313,20,38,16
1,2017-05-04T00:00:00,1,0041600203,1610612764,WAS,Washington,1-2,39,24,32,...,0,0,0,116,0.467,0.880,0.320,26,50,9
2,2017-05-04T00:00:00,2,0041600222,1610612762,UTA,Utah,0-2,15,32,35,...,0,0,0,104,0.452,0.800,0.375,19,39,14
3,2017-05-04T00:00:00,2,0041600222,1610612744,GSW,Golden State,2-0,33,27,32,...,0,0,0,115,0.494,0.850,0.452,33,47,17

In [14]:
# Lets look at specfic games
from nba_py import game
game_id = '0041600222'

In [18]:
boxscore = game.BoxscoreSummary(game_id)

In [19]:
boxscore.inactive_players()

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION
0,201588,George,Hill,3,1610612762,Utah,Jazz,UTA
1,202692,Alec,Burks,10,1610612762,Utah,Jazz,UTA
2,1626172,Kevon,Looney,5,1610612744,Golden State,Warriors,GSW
3,1627745,Damian,Jones,15,1610612744,Golden State,Warriors,GSW

In [20]:
boxscore.game_summary()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,WH_STATUS
0,2017-05-04T00:00:00,2,0041600222,3,Final,20170504/UTAGSW,1610612744,1610612762,2016,4,,ESPN,Q4 - ESPN,1

In [21]:
boxscore.game_info()

               GAME_DATE  ATTENDANCE GAME_TIME
0  THURSDAY, MAY 4, 2017       19596      2:22

In [22]:
boxscore.other_stats()

,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PTS_PAINT,PTS_2ND_CHANCE,PTS_FB,LARGEST_LEAD,LEAD_CHANGES,TIMES_TIED,TEAM_TURNOVERS,TOTAL_TURNOVERS,TEAM_REBOUNDS,PTS_OFF_TO
0,00,1610612744,GSW,Golden State,42,15,19,20,0,0,0,17,3,22
1,00,1610612762,UTA,Utah,42,6,18,0,0,0,1,15,7,24

In [23]:
boxscore.last_meeting()

,GAME_ID,LAST_GAME_ID,LAST_GAME_DATE_EST,LAST_GAME_HOME_TEAM_ID,LAST_GAME_HOME_TEAM_CITY,LAST_GAME_HOME_TEAM_NAME,LAST_GAME_HOME_TEAM_ABBREVIATION,LAST_GAME_HOME_TEAM_POINTS,LAST_GAME_VISITOR_TEAM_ID,LAST_GAME_VISITOR_TEAM_CITY,LAST_GAME_VISITOR_TEAM_NAME,LAST_GAME_VISITOR_TEAM_CITY1,LAST_GAME_VISITOR_TEAM_POINTS
0,0041600222,0041600221,2017-05-02T00:00:00,1610612744,Golden State,Warriors,GSW,106,1610612762,Utah,Jazz,UTA,94

In [25]:
boxscore.season_series()

,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,GAME_DATE_EST,HOME_TEAM_WINS,HOME_TEAM_LOSSES,SERIES_LEADER
0,0041600222,1610612744,1610612762,2017-05-04T00:00:00,2,0,Golden State

In [26]:
boxscore.officials()

   OFFICIAL_ID FIRST_NAME LAST_NAME JERSEY_NUM
0         1195    Derrick  Stafford       9
1         2002    Derrick   Collins       11
2         2534       Zach     Zarba       15

In [29]:
boxscore_scoring = game.BoxscoreScoring(game_id)

In [35]:
boxscore_scoring

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PCT_FGA_2PT,...,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0041600222,1610612762,UTA,Utah,202330,Gordon Hayward,F,,40:09,0.619,...,0.212,0.242,0.273,0.303,0.375,0.625,0.000,1.000,0.273,0.727
1,0041600222,1610612762,UTA,Utah,2207,Joe Johnson,F,,30:05,0.500,...,0.000,0.000,0.000,0.250,0.000,1.000,1.000,0.000,0.667,0.333
2,0041600222,1610612762,UTA,Utah,203497,Rudy Gobert,C,,36:52,1.000,...,0.125,0.000,0.250,1.000,0.750,0.250,0.000,0.000,0.750,0.250
3,0041600222,1610612762,UTA,Utah,204060,Joe Ingles,G,,21:04,0.600,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000
4,0041600222,1610612762,UTA,Utah,202714,Shelvin Mack,G,,30:39,0.545,...,0.500,0.214,0.143,0.143,0.000,1.000,0.333,0.667,0.250,0.750
5,0041600222,1610612762,UTA,Utah,203918,Rodney Hood,,,35:00,0.615,...,0.250,0.000,0.000,0.500,0.250,0.750,0.000,0.000,0.250,0.750
6,0041600222,1610612762,UTA,Utah,203526,Raul Neto,,,8:57,0.000,...,0.000,0.400,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000
7,0041600222,1610612762,UTA,Utah,2564,Boris Diaw,,,12:28,0.600,...,0.000,0.000,0.000,0.571,0.500,0.500,1.000,0.000,0.667,0.333
8,0041600222,1610612762,UTA,Utah,202324,Derrick Favors,,,10:47,1.000,...,0.000,0.333,1.000,0.667,1.000,0.000,0.000,0.000,1.000,0.000
9,0041600222,1610612762,UTA,Utah,203957,Dante Exum,,,13:59,0.333,...,0.000,0.286,0.571,0.286,0.000,1.000,1.000,0.000,0.500,0.500
10,0041600222,1610612762,UTA,Utah,1627762,Joel Bolomboy,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0041600222,1610612762,UTA,Utah,1626168,Trey Lyles,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0041600222,1610612762,UTA,Utah,203481,Jeff Withey,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0041600222,1610612744,GSW,Golden State,201142,Kevin Durant,F,,36:00,0.692,...,0.440,0.520,0.320,0.320,0.500,0.500,0.000,0.000,0.500,0.500
14,0041600222,1610612744,GSW,Golden State,203110,Draymond Green,F,,35:32,0.385,...,0.000,0.095,0.143,0.190,1.000,0.000,1.000,0.000,1.000,0.000
15,0041600222,1610612744,GSW,Golden State,2585,Zaza Pachulia,C,,8:58,1.000,...,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000
16,0041600222,1610612744,GSW,Golden State,202691,Klay Thompson,G,,35:57,0.692,...,0.286,0.000,0.429,0.429,1.000,0.000,1.000,0.000,1.000,0.000
17,0041600222,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:10,0.467,...,0.000,0.087,0.217,0.000,0.333,0.667,0.800,0.200,0.625,0.375
18,0041600222,1610612744,GSW,Golden State,2738,Andre Iguodala,,,34:09,0.750,...,0.000,0.000,0.200,1.000,0.800,0.200,0.000,0.000,0.800,0.200
19,0041600222,1610612744,GSW,Golden State,201580,JaVale McGee,,,9:11,1.000,...,1.000,0.000,0.000,1.000,0.500,0.500,0.000,0.000,0.500,0.500
20,0041600222,1610612744,GSW,Golden State,2733,Shaun Livingston,,,15:00,1.000,...,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000
21,0041600222,1610612744,GSW,Golden State,203949,James Michael McAdoo,,,0:12,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,0041600222,1610612744,GSW,Golden State,203546,Ian Clark,,,9:10,0.333,...,0.000,0.000,0.000,0.250,1.000,0.000,0.500,0.500,0.667,0.333
23,0041600222,1610612744,GSW,Golden State,2561,David West,,,14:43,1.000,...,0.000,0.000,0.000,0.500,1.000,0.000,0.000,0.000,1.000,0.000
24,0041600222,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,1:56,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25,0041600222,1610612744,GSW,Golden State,2440,Matt Barnes,,,1:02,1.000,...,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000

In [43]:
boxscore_usage = game.BoxscoreUsage(game_id)

In [44]:
boxscore_usage

In [45]:
boxscore_usage.sql_players_usage()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,USG_PCT,...,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0041600222,1610612762,UTA,Utah,202330,Gordon Hayward,F,,40:09,0.297,...,0.156,0.139,0.250,0.167,0.167,0.000,0.000,0.200,0.357,0.359
1,0041600222,1610612762,UTA,Utah,2207,Joe Johnson,F,,30:05,0.129,...,0.000,0.000,0.273,0.083,0.000,0.000,0.000,0.059,0.100,0.148
2,0041600222,1610612762,UTA,Utah,203497,Rudy Gobert,C,,36:52,0.158,...,0.448,0.485,0.000,0.083,0.167,1.000,0.333,0.273,0.214,0.205
3,0041600222,1610612762,UTA,Utah,204060,Joe Ingles,G,,21:04,0.177,...,0.333,0.308,0.091,0.375,0.333,0.000,0.333,0.200,0.200,0.070
4,0041600222,1610612762,UTA,Utah,202714,Shelvin Mack,G,,30:39,0.234,...,0.087,0.120,0.364,0.273,0.333,0.000,0.333,0.235,0.200,0.222
5,0041600222,1610612762,UTA,Utah,203918,Rodney Hood,,,35:00,0.187,...,0.125,0.103,0.182,0.200,0.167,0.000,0.000,0.125,0.118,0.108
6,0041600222,1610612762,UTA,Utah,203526,Raul Neto,,,8:57,0.146,...,0.000,0.000,0.500,0.000,1.000,0.000,0.000,0.000,0.400,0.250
7,0041600222,1610612762,UTA,Utah,2564,Boris Diaw,,,12:28,0.188,...,0.286,0.250,0.143,0.000,0.000,0.000,1.000,0.000,0.000,0.219
8,0041600222,1610612762,UTA,Utah,202324,Derrick Favors,,,10:47,0.086,...,0.800,0.833,0.000,0.000,0.000,1.000,0.000,0.000,0.167,0.115
9,0041600222,1610612762,UTA,Utah,203957,Dante Exum,,,13:59,0.274,...,0.111,0.083,0.400,0.667,0.500,0.000,0.000,0.444,0.286,0.184
10,0041600222,1610612762,UTA,Utah,1627762,Joel Bolomboy,,DNP - Coach's Decision,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0041600222,1610612762,UTA,Utah,1626168,Trey Lyles,,DNP - Coach's Decision,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0041600222,1610612762,UTA,Utah,203481,Jeff Withey,,DNP - Coach's Decision,None,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0041600222,1610612744,GSW,Golden State,201142,Kevin Durant,F,,36:00,0.246,...,0.379,0.314,0.280,0.100,0.125,0.500,0.000,0.182,0.526,0.275
14,0041600222,1610612744,GSW,Golden State,203110,Draymond Green,F,,35:32,0.223,...,0.231,0.219,0.214,0.364,0.364,0.250,0.000,0.214,0.250,0.236
15,0041600222,1610612744,GSW,Golden State,2585,Zaza Pachulia,C,,8:58,0.056,...,0.500,0.400,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.083
16,0041600222,1610612744,GSW,Golden State,202691,Klay Thompson,G,,35:57,0.167,...,0.172,0.171,0.250,0.083,0.182,0.000,0.500,0.143,0.045,0.163
17,0041600222,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:10,0.215,...,0.103,0.114,0.241,0.273,0.250,0.000,0.500,0.231,0.222,0.228
18,0041600222,1610612744,GSW,Golden State,2738,Andre Iguodala,,,34:09,0.185,...,0.138,0.139,0.190,0.214,0.143,0.333,0.000,0.188,0.059,0.127
19,0041600222,1610612744,GSW,Golden State,201580,JaVale McGee,,,9:11,0.190,...,0.000,0.182,0.000,0.200,0.000,0.000,0.000,1.000,0.000,0.200
20,0041600222,1610612744,GSW,Golden State,2733,Shaun Livingston,,,15:00,0.149,...,0.167,0.133,0.200,0.333,0.000,0.000,0.000,0.125,0.000,0.051
21,0041600222,1610612744,GSW,Golden State,203949,James Michael McAdoo,,,0:12,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,0041600222,1610612744,GSW,Golden State,203546,Ian Clark,,,9:10,0.381,...,0.143,0.100,0.000,0.333,0.000,0.000,0.000,0.143,0.500,0.571
23,0041600222,1610612744,GSW,Golden State,2561,David West,,,14:43,0.144,...,0.286,0.389,0.000,0.000,0.333,0.500,0.000,0.100,0.000,0.154
24,0041600222,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,1:56,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25,0041600222,1610612744,GSW,Golden State,2440,Matt Barnes,,,1:02,0.500,...,0.000,0.000,0.500,0.000,0.000,0.000,0.000,0.500,0.000,0.500

In [46]:
boxscore_misc = game.BoxscoreMisc(game_id)

In [47]:
boxscore_misc

In [48]:
boxscore_misc.sql_players_misc()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PTS_OFF_TOV,...,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK,BLKA,PF,PFD
0,0041600222,1610612762,UTA,Utah,202330,Gordon Hayward,F,,40:09,9.0,...,7.0,10.0,22.0,9.0,19.0,34.0,0.0,0.0,4.0,5.0
1,0041600222,1610612762,UTA,Utah,2207,Joe Johnson,F,,30:05,0.0,...,0.0,2.0,17.0,15.0,16.0,30.0,0.0,0.0,1.0,1.0
2,0041600222,1610612762,UTA,Utah,203497,Rudy Gobert,C,,36:52,4.0,...,2.0,16.0,17.0,15.0,15.0,34.0,1.0,1.0,6.0,3.0
3,0041600222,1610612762,UTA,Utah,204060,Joe Ingles,G,,21:04,0.0,...,0.0,0.0,11.0,11.0,6.0,16.0,0.0,1.0,2.0,2.0
4,0041600222,1610612762,UTA,Utah,202714,Shelvin Mack,G,,30:39,2.0,...,7.0,2.0,17.0,9.0,13.0,28.0,0.0,1.0,4.0,2.0
5,0041600222,1610612762,UTA,Utah,203918,Rodney Hood,,,35:00,0.0,...,2.0,4.0,15.0,10.0,13.0,34.0,0.0,0.0,2.0,2.0
6,0041600222,1610612762,UTA,Utah,203526,Raul Neto,,,8:57,0.0,...,0.0,0.0,5.0,2.0,4.0,6.0,0.0,0.0,0.0,2.0
7,0041600222,1610612762,UTA,Utah,2564,Boris Diaw,,,12:28,0.0,...,0.0,4.0,5.0,0.0,2.0,8.0,0.0,1.0,0.0,0.0
8,0041600222,1610612762,UTA,Utah,202324,Derrick Favors,,,10:47,3.0,...,0.0,2.0,7.0,0.0,4.0,8.0,1.0,0.0,0.0,1.0
9,0041600222,1610612762,UTA,Utah,203957,Dante Exum,,,13:59,4.0,...,0.0,2.0,4.0,4.0,3.0,12.0,0.0,0.0,4.0,2.0
10,0041600222,1610612762,UTA,Utah,1627762,Joel Bolomboy,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0041600222,1610612762,UTA,Utah,1626168,Trey Lyles,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0041600222,1610612762,UTA,Utah,203481,Jeff Withey,,DNP - Coach's Decision,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0041600222,1610612744,GSW,Golden State,201142,Kevin Durant,F,,36:00,8.0,...,11.0,8.0,12.0,4.0,16.0,30.0,1.0,0.0,2.0,10.0
14,0041600222,1610612744,GSW,Golden State,203110,Draymond Green,F,,35:32,3.0,...,0.0,4.0,16.0,6.0,16.0,32.0,1.0,0.0,3.0,5.0
15,0041600222,1610612744,GSW,Golden State,2585,Zaza Pachulia,C,,8:58,0.0,...,0.0,2.0,0.0,0.0,5.0,4.0,0.0,0.0,0.0,0.0
16,0041600222,1610612744,GSW,Golden State,202691,Klay Thompson,G,,35:57,6.0,...,4.0,6.0,15.0,4.0,15.0,30.0,0.0,1.0,2.0,1.0
17,0041600222,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:10,5.0,...,0.0,0.0,17.0,4.0,16.0,32.0,0.0,1.0,3.0,4.0
18,0041600222,1610612744,GSW,Golden State,2738,Andre Iguodala,,,34:09,2.0,...,0.0,10.0,18.0,6.0,13.0,32.0,1.0,0.0,3.0,1.0
19,0041600222,1610612744,GSW,Golden State,201580,JaVale McGee,,,9:11,0.0,...,4.0,4.0,4.0,0.0,2.0,6.0,0.0,0.0,3.0,0.0
20,0041600222,1610612744,GSW,Golden State,2733,Shaun Livingston,,,15:00,0.0,...,0.0,2.0,9.0,2.0,3.0,12.0,0.0,0.0,1.0,0.0
21,0041600222,1610612744,GSW,Golden State,203949,James Michael McAdoo,,,0:12,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0041600222,1610612744,GSW,Golden State,203546,Ian Clark,,,9:10,0.0,...,0.0,2.0,5.0,2.0,2.0,10.0,0.0,0.0,1.0,2.0
23,0041600222,1610612744,GSW,Golden State,2561,David West,,,14:43,0.0,...,0.0,2.0,9.0,2.0,2.0,16.0,1.0,0.0,1.0,0.0
24,0041600222,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,1:56,0.0,...,0.0,0.0,2.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
25,0041600222,1610612744,GSW,Golden State,2440,Matt Barnes,,,1:02,0.0,...,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [49]:
boxscore_misc.sql_team_misc()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK,BLKA,PF,PFD
0,0041600222,1610612762,Jazz,UTA,Utah,240:00,22.0,6.0,18.0,42.0,24.0,15.0,19.0,42.0,2,4,23,20
1,0041600222,1610612744,Warriors,GSW,Golden State,240:00,24.0,15.0,19.0,42.0,22.0,6.0,18.0,42.0,4,2,20,23

In [51]:
boxscore_advacned = game.BoxscoreAdvanced(game_id)

In [52]:
boxscore_advacned

In [54]:
boxscore_advacned.sql_players_advanced()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,OFF_RATING,...,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE
0,0041600222,1610612762,UTA,Utah,202330,Gordon Hayward,F,,40:09,105.8,...,12.9,0.000,0.132,0.068,6.5,0.595,0.661,0.297,103.84,0.140
1,0041600222,1610612762,UTA,Utah,2207,Joe Johnson,F,,30:05,81.2,...,25.0,0.000,0.000,0.000,8.3,0.500,0.500,0.129,104.80,0.036
2,0041600222,1610612762,UTA,Utah,203497,Rudy Gobert,C,,36:52,96.2,...,0.0,0.083,0.342,0.216,7.4,0.667,0.643,0.158,104.13,0.137
3,0041600222,1610612762,UTA,Utah,204060,Joe Ingles,G,,21:04,97.3,...,11.1,0.000,0.235,0.118,33.3,0.300,0.300,0.177,98.07,0.012
4,0041600222,1610612762,UTA,Utah,202714,Shelvin Mack,G,,30:39,96.3,...,20.2,0.036,0.074,0.055,15.2,0.500,0.549,0.234,103.45,0.057
5,0041600222,1610612762,UTA,Utah,203918,Rodney Hood,,,35:00,98.2,...,11.8,0.000,0.097,0.047,11.8,0.308,0.308,0.187,103.05,0.007
6,0041600222,1610612762,UTA,Utah,203526,Raul Neto,,,8:57,106.6,...,41.0,0.000,0.000,0.000,0.0,0.750,0.868,0.146,98.25,0.173
7,0041600222,1610612762,UTA,Utah,2564,Boris Diaw,,,12:28,124.8,...,16.7,0.000,0.250,0.125,0.0,0.700,0.700,0.188,98.10,0.129
8,0041600222,1610612762,UTA,Utah,202324,Derrick Favors,,,10:47,125.2,...,0.0,0.143,0.800,0.417,0.0,1.000,0.798,0.086,94.90,0.124
9,0041600222,1610612762,UTA,Utah,203957,Dante Exum,,,13:59,129.3,...,18.4,0.000,0.083,0.042,18.4,0.417,0.509,0.274,101.68,0.017
10,0041600222,1610612762,UTA,Utah,1627762,Joel Bolomboy,,DNP - Coach's Decision,None,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN
11,0041600222,1610612762,UTA,Utah,1626168,Trey Lyles,,DNP - Coach's Decision,None,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN
12,0041600222,1610612762,UTA,Utah,203481,Jeff Withey,,DNP - Coach's Decision,None,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN
13,0041600222,1610612744,GSW,Golden State,201142,Kevin Durant,F,,36:00,117.0,...,25.4,0.000,0.333,0.159,3.6,0.462,0.638,0.246,103.89,0.197
14,0041600222,1610612744,GSW,Golden State,203110,Draymond Green,F,,35:32,117.0,...,24.7,0.032,0.200,0.115,16.4,0.731,0.733,0.223,103.18,0.152
15,0041600222,1610612744,GSW,Golden State,2585,Zaza Pachulia,C,,8:58,141.2,...,0.0,0.000,0.500,0.182,0.0,1.000,1.000,0.056,92.18,0.070
16,0041600222,1610612744,GSW,Golden State,202691,Klay Thompson,G,,35:57,110.4,...,30.0,0.030,0.156,0.092,5.0,0.538,0.538,0.167,105.16,0.118
17,0041600222,1610612744,GSW,Golden State,201939,Stephen Curry,G,,38:10,123.5,...,27.0,0.029,0.091,0.059,11.6,0.700,0.724,0.215,102.95,0.122
18,0041600222,1610612744,GSW,Golden State,2738,Andre Iguodala,,,34:09,106.7,...,21.1,0.032,0.118,0.077,15.8,0.417,0.417,0.185,104.15,0.056
19,0041600222,1610612744,GSW,Golden State,201580,JaVale McGee,,,9:11,105.3,...,0.0,0.250,0.000,0.111,25.0,0.667,0.667,0.190,96.38,0.000
20,0041600222,1610612744,GSW,Golden State,2733,Shaun Livingston,,,15:00,127.3,...,28.6,0.000,0.143,0.077,28.6,0.333,0.333,0.149,96.96,0.016
21,0041600222,1610612744,GSW,Golden State,203949,James Michael McAdoo,,,0:12,0.0,...,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,120.00,0.000
22,0041600222,1610612744,GSW,Golden State,203546,Ian Clark,,,9:10,77.8,...,0.0,0.000,0.125,0.071,25.0,0.667,0.667,0.381,96.56,0.162
23,0041600222,1610612744,GSW,Golden State,2561,David West,,,14:43,84.5,...,0.0,0.231,0.267,0.250,0.0,0.400,0.400,0.144,102.48,0.187
24,0041600222,1610612744,GSW,Golden State,1627775,Patrick McCaw,,,1:56,50.0,...,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.77,0.000
25,0041600222,1610612744,GSW,Golden State,2440,Matt Barnes,,,1:02,200.0,...,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.500,90.12,0.222

In [55]:
boxscore_advacned.sql_team_advanced()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,OFF_RATING,DEF_RATING,NET_RATING,AST_PCT,...,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,PACE,PIE
0,0041600222,1610612762,Jazz,UTA,Utah,240:00,101.2,113.0,-11.8,0.500,...,15.0,0.116,0.791,0.453,14.591,0.524,0.560,0.198,102.3,0.403
1,0041600222,1610612744,Warriors,GSW,Golden State,240:00,113.0,101.2,11.8,0.786,...,22.9,0.209,0.884,0.547,16.699,0.576,0.613,0.200,102.3,0.597

In [56]:
boxscore_fourfactors = game.BoxscoreFourFactors(game_id)

In [57]:
boxscore_fourfactors

In [59]:
boxscore_fourfactors.sql_team_four_factors()

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0041600222,1610612762,Jazz,UTA,Utah,240:00,0.524,0.238,0.146,0.116,0.576,0.235,0.167,0.209
1,0041600222,1610612744,Warriors,GSW,Golden State,240:00,0.576,0.235,0.167,0.209,0.524,0.238,0.146,0.116

In [60]:
boxscore_playbyplay = game.PlayByPlay(game_id)

In [61]:
boxscore_playbyplay

In [62]:
boxscore_playbyplay.info()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
0,0041600222,0,12,0,1,10:43 PM,12:00,None,None,None,None,None
1,0041600222,1,10,0,1,10:43 PM,12:00,Jump Ball Pachulia vs. Gobert: Tip to Green,None,None,None,None
2,0041600222,2,1,63,1,10:44 PM,11:42,Durant 16' Fadeaway Jumper (2 PTS) (Curry 1 AST),None,None,0 - 2,2
3,0041600222,3,6,27,1,10:44 PM,11:27,Durant Personal Block Foul (P1.T1) (D.Collins),None,None,None,None
4,0041600222,4,2,52,1,10:44 PM,11:19,Green BLOCK (1 BLK),None,MISS Gobert Alley Oop Dunk,None,None
5,0041600222,5,4,0,1,10:44 PM,11:19,Pachulia REBOUND (Off:0 Def:1),None,None,None,None
6,0041600222,6,1,79,1,10:44 PM,11:09,Green 26' 3PT Pullup Jump Shot (3 PTS) (Durant...,None,None,0 - 5,5
7,0041600222,7,1,1,1,10:45 PM,10:44,None,None,Johnson 26' 3PT Jump Shot (3 PTS) (Mack 1 AST),3 - 5,2
8,0041600222,8,2,1,1,10:45 PM,10:24,MISS Thompson 4' Jump Shot,None,Gobert BLOCK (1 BLK),None,None
9,0041600222,9,4,0,1,10:45 PM,10:23,Thompson REBOUND (Off:1 Def:0),None,None,None,None
10,0041600222,10,1,63,1,10:45 PM,10:17,Green 27' 3PT Fadeaway Jumper (6 PTS) (Thompso...,None,None,3 - 8,5
11,0041600222,11,5,1,1,10:46 PM,10:07,Durant STEAL (1 STL),None,Ingles Bad Pass Turnover (P1.T1),None,None
12,0041600222,12,1,44,1,10:46 PM,9:55,Thompson 1' Reverse Layup (2 PTS) (Curry 2 AST),None,None,3 - 10,7
13,0041600222,13,2,1,1,10:46 PM,9:39,None,None,MISS Hayward 26' 3PT Jump Shot,None,None
14,0041600222,14,4,0,1,10:46 PM,9:39,WARRIORS Rebound,None,None,None,None
15,0041600222,15,6,3,1,10:46 PM,9:39,None,None,Gobert L.B.FOUL (P1.T1) (D.Collins),None,None
16,0041600222,16,1,42,1,10:47 PM,9:20,Pachulia 2' Driving Layup (2 PTS) (Durant 2 AST),None,None,3 - 12,9
17,0041600222,17,9,1,1,10:47 PM,9:20,None,None,Jazz Timeout: Regular (Reg.1 Short 0),None,None
18,0041600222,19,2,58,1,10:50 PM,8:58,None,None,MISS Johnson 7' Turnaround Hook Shot,None,None
19,0041600222,20,4,0,1,10:50 PM,8:58,Pachulia REBOUND (Off:0 Def:2),None,None,None,None
20,0041600222,21,2,80,1,10:50 PM,8:42,MISS Curry 16' Step Back Jump Shot,None,None,None,None
21,0041600222,22,4,0,1,10:50 PM,8:41,None,None,Gobert REBOUND (Off:0 Def:1),None,None
22,0041600222,23,1,79,1,10:51 PM,8:31,None,None,Mack 28' 3PT Pullup Jump Shot (3 PTS),6 - 12,6
23,0041600222,24,2,78,1,10:51 PM,8:13,MISS Durant 11' Floating Jump Shot,None,None,None,None
24,0041600222,25,4,0,1,10:51 PM,8:12,None,None,Gobert REBOUND (Off:0 Def:2),None,None
25,0041600222,26,7,5,1,10:51 PM,8:08,Durant Violation:Kicked Ball (D.Collins),None,None,None,None
26,0041600222,27,5,1,1,10:51 PM,7:59,Green STEAL (1 STL),None,Mack Bad Pass Turnover (P1.T2),None,None
27,0041600222,28,6,1,1,10:52 PM,7:57,None,None,Johnson P.FOUL (P1.T2) (D.Stafford),None,None
28,0041600222,29,1,79,1,10:52 PM,7:49,Thompson 11' Pullup Jump Shot (4 PTS) (Durant ...,None,None,6 - 14,8
29,0041600222,30,5,1,1,10:52 PM,7:32,Curry STEAL (1 STL),None,Ingles Bad Pass Turnover (P2.T3),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
421,0041600222,478,8,0,4,12:58 AM,2:52,SUB: Thompson FOR Livingston,None,None,None,None
422,0041600222,479,1,86,4,12:59 AM,2:34,None,None,Hayward 10' Turnaround Fadeaway (33 PTS),100 - 109,9
423,0041600222,480,2,1,4,12:59 AM,2:16,MISS Durant 12' Jump Shot,None,None,None,None
424,0041600222,481,4,0,4,12:59 AM,2:15,None,None,Hood REBOUND (Off:0 Def:3),None,None
425,0041600222,482,1,1,4,12:59 AM,2:05,None,None,Hood 4' Jump Shot (8 PTS),102 - 109,7
426,0041600222,483,1,108,4,12:59 AM,1:45,Iguodala Cutting Dunk Shot (10 PTS) (Durant 7...,None,None,102 - 111,9
427,0041600222,484,9,1,4,1:00 AM,1:45,None,None,Jazz Timeout: Regular (Reg.5 Short 1),None,None
428,0041600222,485,2,79,4,1:02 AM,1:37,None,None,MISS Hood 27' 3PT Pullup Jump Shot,None,None
429,0041600222,486,4,0,4,1:02 AM,1:36,Iguodala REBOUND (Off:1 Def:4),None,None,None,None
430,0041600222,487,2,1,4,1:02 AM,1:18,MISS Durant 7' Jump Shot,None,None,None,None
431,0041600222,488,4,0,4,1:02 AM,1:18,None,None,Mack REBOUND (Off:0 Def:2),None,None
432,0041600222,489,2,5,4,1:02 AM,1:09,None,None,MISS Gobert 3' Layup,None,None
433,0041600222,490,4,0,4,1:02 AM,1:08,Durant REBOUND (Off:0 Def:11),None,None,None,None
434,0041600222,491,2,1,4,1:02 AM,0:45,MISS Iguodala 24' 3PT Jump Shot,None,None,None,None
435,0041600222,492,4,0,4,1:02 AM,0:44,None,None,Hayward REBOUND (Off:0 Def:5),None,None
436,0041600222,493,2,5,4,1:03 AM,0:39,None,None,MISS Hayward 3' Layup,None,None
437,0041600222,494,4,0,4,1:03 AM,0:38,Thompson REBOUND (Off:1 Def:5),None,None,None,None
438,0041600222,495,6,2,4,1:03 AM,0:18,None,None,Gobert S.FOUL (P5.PN) (D.Stafford),None,None
439,0041600222,496,3,11,4,1:03 AM,0:18,Durant Free Throw 1 of 2 (22 PTS),None,None,102 - 112,10
440,0041600222,498,3,12,4,1:03 AM,0:18,Durant Free Throw 2 of 2 (23 PTS),None,None,102 - 113,11
441,0041600222,500,2,1,4,1:04 AM,0:11,None,None,MISS Hayward 25' 3PT Jump Shot,None,None
442,0041600222,501,4,0,4,1:04 AM,0:11,None,None,Mack REBOUND (Off:1 Def:2),None,None
443,0041600222,502,5,1,4,1:04 AM,0:07,None,None,Mack Bad Pass Turnover (P3.T15),None,None
444,0041600222,503,6,3,4,1:04 AM,0:07,None,None,Gobert L.B.FOUL (P6.PN) (Z.Zarba),None,None
445,0041600222,505,3,11,4,1:05 AM,0:07,Durant Free Throw 1 of 2 (24 PTS),None,None,102 - 114,12
446,0041600222,507,3,12,4,1:05 AM,0:07,Durant Free Throw 2 of 2 (25 PTS),None,None,102 - 115,13
447,0041600222,509,6,1,4,1:05 AM,0:05,Green P.FOUL (P3.PN) (D.Collins),None,None,None,None
448,0041600222,510,3,11,4,1:05 AM,0:05,None,None,Mack Free Throw 1 of 2 (13 PTS),103 - 115,12
449,0041600222,512,3,12,4,1:05 AM,0:05,None,None,Mack Free Throw 2 of 2 (14 PTS),104 - 115,11
450,0041600222,514,13,0,4,1:06 AM,0:00,None,None,None,104 - 115,11

In [63]:
boxscore_playbyplay.available_video()

   VIDEO_AVAILABLE_FLAG
0                     1

In [68]:
boxscore_hustlestats = game.HustleStats(game_id)

AttributeError: 'module' object has no attribute 'HustleStats'